-- 연도별로 묶어서 max 해야 함

SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR, 
    MAX(SIZE_OF_COLONY) OVER (PARTITION BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA 
ORDER BY YEAR, YEAR_DEV;