SELECT A.ID, B.FISH_NAME, A.LENGTH
FROM FISH_INFO A
INNER JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN (SELECT 
    FISH_TYPE, MAX(LENGTH) AS MAX_LEN
      FROM FISH_INFO
      GROUP BY FISH_TYPE
     ) C
ON A.FISH_TYPE = C.FISH_TYPE
AND MAX_LEN = A.LENGTH;