-- 각 성분 타입과 성분 타입에 대한 아이스크림 총 주문량
-- group by 성분 타입
-- 그 안에서 sum 해준다?

SELECT INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF A
JOIN ICECREAM_INFO B 
ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;